name: CI Testing
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install flvtool2
        run: sudo gem install flvtool2
      - name: Install ffmpeg
        run: sudo apt install -y ffmpeg
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Generate coverage report
        run: npm run coverage
      - name: Store coveralls coverage
        uses: coverallsapp/github-action@v2
        with:
          flag-name: linux-node-${{ matrix.node }}
          parallel: true
      # - name: Upload to codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   with:
      #     files: coverage/lcov.info
      #     name: ubuntu-latest-node-${{ matrix.node }}

  upload-coverage:
    name: Upload coverage
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Upload to coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "linux-node-22"
